content: |-
  {{ .Header }}

  ## Example

  ```hcl
  {{ include "examples/confluent_platform/.main.tf.docs" }}
  ```

  ## Usage

  Release the Confluent Platform with:

  ```bash
  cd examples/complete
  terraform init
  terraform apply
  ```

  ## Troubleshooting

  ```
  Error: Failed to determine GroupVersionResource for manifest
  ```

  This Terraform module uses the [kubernetes_manifest](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest) resource to deploy CFK custom resources. The following excerpt is from [Beta Support for CRDs in the Terraform Provider for Kubernetes](https://www.hashicorp.com/blog/beta-support-for-crds-in-the-terraform-provider-for-kubernetes):

  > Custom resource definitions must be applied before custom resources. As above, this is because the provider queries the Kubernetes API for the OpenAPI specification for the resource supplied in the manifest attribute. If the CRD doesn’t exist in the OpenAPI specification during plan time then Terraform can’t use it to create custom resources.

  Please see [Troubleshoot Confluent for Kubernetes](https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/troubleshooting) for other troubleshooting needs.

   ## Tests

  Run Terratest using the [Makefile](https://github.com/aidanmelen/terraform-aws-security-group-v2/tree/main/Makefile) targets:

  1. `make setup`
  2. `make tests`

  ### Results

  ```
  {{ include "test/.terratest.docs" }}
  ```

  ## Makefile Targets

  ```
  {{ include ".makefile.docs" }}
  ```

  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
