content: |-
  {{ .Header }}

  ## Example

  ### Confluent Platform

  ```hcl
  {{ include "examples/complete/.main.tf.docs" }}
  ```

  ## Usage

  ### Prerequisites

  The Confluent for Kubernetes CRDs must installed on the Kubernetes cluster before the first Terraform apply of the Confluent Platform. Install the CRDs with:

  ```bash
  kubectl config set-cluster docker-desktop
  kubectl apply -f ./crds/2.4.0
  ```

  Please see the [Makefile](https://github.com/aidanmelen/terraform-kubernetes-confluent-platform/blob/main/Makefile) for more information.

  ### Confluent Platform

  Release the Confluent Platform with:

  ```bash
  cd examples/complete
  terraform init
  terraform apply
  ```

  ### Troubleshooting

  ```
  Error: Failed to determine GroupVersionResource for manifest
  ```

  This happens when you attempt to apply the Confluent Platform Terraform without first applying the Confluent for Kubernetes CRDs. Please see [Prerequisites](#prerequisites) for more information.

  ## Tests

  Run Terratest using the [Makefile](./Makefile) targets:

  1. `make install`
  2. `make tests`

  ## Makefile Targets

  ```
  {{ include ".make.docs" }}
  ```

  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
