content: |-
  {{ .Header }}

  ## Usage

  ```hcl
  {{ include "examples/quickstart_deploy/.confluent_platform.tf.docs" }}
  ```

  Please see the [confluent_platform example](examples/quickstart_deploy/confluent_platform) for more information.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
