content: |-
  {{ .Header }}

  ## Example

  ### Confluent Platform

  ```hcl
  {{ include "examples/confluent_platform/.main.tf.docs" }}
  ```

  ## Usage

  Release the Confluent Platform with:

  ```bash
  cd examples/complete
  terraform init
  terraform apply
  ```

  ### Troubleshooting

  ```
  Error: Failed to determine GroupVersionResource for manifest
  ```

  This happens when you attempt to apply the Confluent Platform Terraform without first creating the Confluent for Kubernetes CRDs. Please see [Prerequisites](#prerequisites) for more information.

  ## Tests

  Run Terratest using the [Makefile](./Makefile) targets:

  1. `make setup`
  2. `make tests`

  ## Makefile Targets

  ```
  {{ include ".make.docs" }}
  ```

  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
