content: |-
  {{ .Header }}

  ## Example

  ### Confluent Platform

  ```hcl
  {{ include "examples/complete/.main.tf.docs" }}
  ```

  ## Usage

  ### Confluent Platform

  First, install the CFK CDRs on the Kubernetes Cluster. For example:

  ```bash
  make install-cfk-crds
  ```

  Please see the [Confluent for Kubernetes Quickstart](https://docs.confluent.io/operator/current/co-quickstart.html#co-long-quickstart) for more information.

  Then release the Confluent Platform with

  ```bash
  cd examples/complete
  terraform init
  terraform apply
  ```

  ## Troubleshooting

  ```
  Error: Failed to determine GroupVersionResource for manifest
  ```

  This happens when you attempt to apply the Confluent Platform Terraform without first applying the Confluent for Kubernetes CRDs. Please see [Prerequisites](#prerequisites) for more information.

  ## Tests

  Run Terratest using the [Makefile](./Makefile) targets:

  1. `make install`
  2. `make tests`

  ## Makefile Targets

  ```
  {{ include ".make.docs" }}
  ```

  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
