content: |-
  {{ .Header }}
  ## Example

  ```hcl
  {{ include "../../examples/kafka_topic/.main.tf.docs" }}
  ```

  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
