content: |-
  {{ .Header }}
  ## Example

  ```hcl
  {{ include "../../examples/kafka_topic/main.tf" }}
  ```

  {{ .Requirements }}
  {{ .Providers }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
