apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: confluent
spec:
  containers:
  - name: kafka-client
    image: confluentinc/cp-server:7.2.0
    command:
      - "sleep"
      - "infinity"
